# Generated by Django 3.0 on 2021-06-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('auther', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
